# Docker Compose to run app + PostgreSQL
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-01
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  fastapi:
    image: tranhuytu37/rfx_docker:latest
    build: 
      context: ./
      target: fastapi-app
      dockerfile: Dockerfile
    container_name: fastapi-01
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      HOST: db
    volumes:
      - .:/app
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
volumes:
  postgres_data:
    driver: local
  cache:
    driver: local
